set(headers ${headers}
    include/PCH.h
    include/ActorValueList.h
    include/AHZActorInfo.h
    include/AHZArmorInfo.h
    include/AHZConsole.h
    include/AHZExternalFormTable.h 
    include/AHZForEachScriptObjectFunctor.h
    include/AHZFormLookup.h        
    include/AHZLUTObject.h
    include/AHZPapyrusMoreHud.h    
    include/AHZPlayerInfo.h        
    include/AHZScaleform.h
    include/AHZScaleformHook.h     
    include/AHZUtilities.h
    include/AHZVanillaFormTable.h  
    include/AHZWeaponInfo.h        
    include/Events.h
    include/HashUtil.h
    include/IForEachScriptObjectFunctor.h
    include/Offsets.h
    include/Papyrus.h
    include/Patches.h
    include/Scaleform.h
    include/version.h
)